jenkins:
  image: jenkins/jenkins:lts-alpine
  ports:
    - "8080:8080"
    - "5000:5000"
  volumes:
    - ./data:/var/jenkins_home
  environment:
    - JAVA_OPTS=-Dhudson.footerURL=http://jenkins.easypi.pro
  restart: always
